---
apiVersion: v1
kind: Service
metadata:
  name: zekeb-test-service
  labels:
    username: zekeb
    env: test
spec:
  type: ClusterIP
  selector:
    app: zekeb-test-redis
  ports:
  - name: helloflask
    port: 6379
    targetPort: 6379
