---
apiVersion: v1
kind: Service
metadata:
  name: zekeb-test-flask-service
  labels:
    username: zekeb
    env: test
spec:
  type: ClusterIP
  selector:
    app: zekeb-test-flask
  ports:
  - name: helloflask
    port: 5000
    targetPort: 5000
